name: Crear archivo TXT

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Crear archivo TXT
        run: |
          touch archivo.txt
          echo "Este es un archivo de ejemplo." > archivo.txt
      - name: Confirmar cambios
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add archivo.txt
          git commit -m "Crear archivo TXT"
          git push
